### ISSUE TITLE
Minor performance related issues 

### ISSUE THREAD

**Issue by ColleagueRiley** [mitjafelicijan/cord.h#1]
I didn't do this as a pull request because 

1) I didn't change much code but I added notes

2) It's mainly just for you to look at

[cord.h.txt](https://github.com/mitjafelicijan/cord.h/files/11983597/cord.h.txt)
(this is a .txt file so it can be uploaded to the issue, but it's actually just an .h file)

**Comment by mitjafelicijan** [comment]
@ColleagueRiley I checked it out roughly and it seems legit. I will merge this into the code. Thank you for the patch :+1:
